/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/system/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current/latest version info for the in-app update flow */
        get: operations["getSystemVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active login sessions — who's logged in, when last seen, and what they're playing right now */
        get: operations["getAdminSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every account */
        get: operations["getAdminUsers"];
        put?: never;
        /** Create another account to share the server with */
        post: operations["createAdminUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Promote/demote an account (cannot demote your own) */
        patch: operations["updateAdminUserRole"];
        trace?: never;
    };
    "/api/admin/users/{userId}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin sets a user's password directly, bypassing the email flow (signs out that user's sessions) */
        post: operations["setAdminUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an account (cannot delete your own) */
        delete: operations["deleteAdminUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings/smtp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current outgoing-mail configuration (password never returned) */
        get: operations["getSMTPSettings"];
        /** Configure outgoing mail (any standard SMTP provider). Leave password blank to keep the existing one. */
        put: operations["updateSMTPSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the first-run admin account still needs to be created */
        get: operations["getSetupStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create the first admin account (only works while needsSetup is true) */
        post: operations["setupAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in and start a session */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user, their profiles, and the active profile (if any) */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the current account's email and/or username (either optional, at least one required) */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password-reset code by email (always 200, doesn't leak account existence) */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a password using the emailed code */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/send-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email a verification code to the account's current address (requires an email to already be set) */
        post: operations["sendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm the emailed verification code, marking the account's email as verified */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List profiles for the current account */
        get: operations["listProfiles"];
        put?: never;
        /** Add a profile (e.g. a kid profile with a PIN) to the current account */
        post: operations["createProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{profileId}/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select the active profile for this session ("who's watching") */
        post: operations["selectProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured libraries */
        get: operations["listLibraries"];
        put?: never;
        /** Add a new library (folder or M3U source) */
        post: operations["createLibrary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/libraries/{libraryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unregister a library (never touches files on disk — admin only) */
        delete: operations["deleteLibrary"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/libraries/{libraryId}/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a rescan of a library */
        post: operations["triggerLibraryScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/libraries/{libraryId}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a file directly into a library's root (requires a writable path — see CreateLibraryRequest.managed), then rescans it */
        post: operations["uploadToLibrary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/libraries/{libraryId}/root": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse a library's top level (root categories + root-level items) */
        get: operations["getLibraryRoot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/libraries/{libraryId}/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A library's most-recently-added items, flattened across all its categories */
        get: operations["getLibraryRecent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/continue-watching": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Items the active profile started but hasn't finished, most-recent first */
        get: operations["getContinueWatching"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A single category's own name/path — used to rebuild breadcrumbs after a page reload */
        get: operations["getCategory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{categoryId}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse a category's subcategories and playable items */
        get: operations["getCategoryChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media-items/{mediaItemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get media item detail */
        get: operations["getMediaItem"];
        put?: never;
        post?: never;
        /** Permanently delete this item's row AND its underlying file (admin only, irreversible) */
        delete: operations["deleteMediaItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media-items/{mediaItemId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Direct-play (Range-served) or transcoded (HLS) playback */
        get: operations["streamMediaItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media-items/{mediaItemId}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generated thumbnail for a photo (404 if none was generated, e.g. undecodable formats like HEIC) */
        get: operations["getThumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media-items/{mediaItemId}/siblings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Other items in the same folder, ordered by episode number when available — the "More from Season X" row, and how the player finds what's next */
        get: operations["getMediaItemSiblings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media-items/{mediaItemId}/show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every episode of the show this item belongs to, across the whole library, grouped by season */
        get: operations["getShow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media-items/{mediaItemId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report playback position for the active profile */
        post: operations["updateProgress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get M3U channel detail */
        get: operations["getChannel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{channelId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirects to the channel's external stream URL (live, non-seekable) */
        get: operations["streamChannel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            /** @example ok */
            status?: string;
        };
        SystemVersion: {
            current?: string;
            latestAvailable?: string | null;
            /** @enum {string} */
            updateMechanism?: "none" | "binary" | "docker-sidecar";
            updateCheckEnabled?: boolean;
        };
        Library: {
            id?: number;
            name?: string;
            rootPath?: string;
            /** @enum {string} */
            type?: "FOLDER" | "PHOTO" | "M3U";
            /** Format: date-time */
            lastScannedAt?: string | null;
        };
        CreateLibraryRequest: {
            name: string;
            /** @description Required unless managed is true */
            rootPath?: string;
            /** @enum {string} */
            type: "FOLDER" | "PHOTO" | "M3U";
            /** @description Root the library under the server's writable uploads directory instead of a host-mounted rootPath, so it can be uploaded into from the web UI */
            managed?: boolean;
        };
        Category: {
            id?: number;
            name?: string;
            path?: string;
            parentCategoryId?: number | null;
        };
        Progress: {
            positionSeconds?: number;
            watched?: boolean;
        };
        /** @description A playable browse-listing entry — a local video/photo (itemType=media_item), an M3U channel (itemType=channel), or a synthetic grouped tile standing in for a whole TV show (itemType=show, id is one representative episode's id — see GET /api/media-items/{id}/show) — sharing one shape so the browse API and client don't need to special-case the source. */
        MediaItem: {
            id?: number;
            /** @enum {string} */
            itemType?: "media_item" | "channel" | "show";
            title?: string;
            filePath?: string;
            durationSeconds?: number | null;
            mediaType?: string;
            progress?: components["schemas"]["Progress"] | null;
            /** @description TMDb poster artwork, when a match was found (requires an admin-configured TMDb API key) */
            posterUrl?: string | null;
            /** @description TMDb backdrop artwork, when a match was found */
            backdropUrl?: string | null;
            /** @description TMDb synopsis, when a match was found */
            overview?: string | null;
            /** @description TMDb vote average, when a match was found */
            rating?: number | null;
            /** @description Set only for TV episodes */
            showTitle?: string | null;
            seasonNumber?: number | null;
            episodeNumber?: number | null;
        };
        UpdateProgressRequest: {
            positionSeconds: number;
            durationSeconds?: number | null;
            watched?: boolean;
        };
        User: {
            id?: number;
            username?: string;
            /** @enum {string} */
            role?: "admin" | "user";
            email?: string | null;
            emailVerified?: boolean;
        };
        SMTPSettings: {
            host?: string;
            port?: number;
            username?: string;
            fromAddress?: string;
            configured?: boolean;
        };
        SMTPSettingsUpdate: {
            host: string;
            port?: number;
            username?: string;
            /** @description Leave blank to keep the existing password */
            password?: string;
            fromAddress?: string;
        };
        Profile: {
            id?: number;
            displayName?: string;
            avatar?: string | null;
            isKid?: boolean;
        };
        MeResponse: {
            user?: components["schemas"]["User"];
            profiles?: components["schemas"]["Profile"][];
            activeProfileId?: number | null;
            /** @description Returned by login and first-run setup only. Native (desktop/ mobile) clients persist it and send it as `Authorization: Bearer <token>`, since their cross-site session cookie can't be stored without HTTPS. Browsers ignore it and keep using the cookie. */
            sessionToken?: string;
        };
        SetupAdminRequest: {
            username: string;
            password: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        CreateProfileRequest: {
            displayName: string;
            isKid?: boolean;
            pin?: string;
        };
        NowPlaying: {
            title?: string;
            /** @enum {string} */
            itemType?: "media_item" | "channel";
            isLive?: boolean;
            positionSeconds?: number;
        };
        AdminSession: {
            sessionId?: string;
            username?: string;
            profileName?: string | null;
            isKid?: boolean;
            /** Format: date-time */
            loginAt?: string;
            /** Format: date-time */
            lastSeenAt?: string | null;
            nowPlaying?: components["schemas"]["NowPlaying"] | null;
        };
        CategoryChildren: {
            subcategories?: components["schemas"]["Category"][];
            items?: components["schemas"]["MediaItem"][];
        };
        ShowSeason: {
            seasonNumber?: number;
            episodes?: components["schemas"]["MediaItem"][];
        };
        CastMember: {
            name?: string;
            character?: string;
            photoUrl?: string | null;
        };
        Show: {
            title?: string;
            overview?: string | null;
            posterUrl?: string | null;
            backdropUrl?: string | null;
            cast?: components["schemas"]["CastMember"][];
            seasons?: components["schemas"]["ShowSeason"][];
        };
    };
    responses: never;
    parameters: {
        LibraryId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getSystemVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemVersion"];
                };
            };
        };
    };
    getAdminSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSession"][];
                };
            };
        };
    };
    getAdminUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    createAdminUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                    /** @enum {string} */
                    role?: "admin" | "user";
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Username already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAdminUserRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    role: "admin" | "user";
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setAdminUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    newPassword: string;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAdminUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSMTPSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SMTP settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SMTPSettings"];
                };
            };
        };
    };
    updateSMTPSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SMTPSettingsUpdate"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setup status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        needsSetup?: boolean;
                    };
                };
            };
        };
    };
    setupAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupAdminRequest"];
            };
        };
        responses: {
            /** @description Admin account created and session started */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email?: string;
                    username?: string;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Username already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                };
            };
        };
        responses: {
            /** @description If the account has an email on file, a reset code was sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    code: string;
                    newPassword: string;
                };
            };
        };
        responses: {
            /** @description Password changed, all sessions for the account signed out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Code sent (or logged, if SMTP isn't configured) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            /** @description Email verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"][];
                };
            };
        };
    };
    createProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProfileRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    selectProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    pin?: string;
                };
            };
        };
        responses: {
            /** @description Profile selected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    listLibraries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Libraries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Library"][];
                };
            };
        };
    };
    createLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLibraryRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Library"];
                };
            };
        };
    };
    deleteLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    triggerLibraryScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scan started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadToLibrary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Uploaded, rescan started */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLibraryRoot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Root of the library */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryChildren"];
                };
            };
        };
    };
    getLibraryRecent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                libraryId: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recently added items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaItem"][];
                };
            };
        };
    };
    getContinueWatching: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description In-progress items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaItem"][];
                };
            };
        };
    };
    getCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    getCategoryChildren: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Children of the category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryChildren"];
                };
            };
        };
    };
    getMediaItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaItemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaItem"];
                };
            };
        };
    };
    deleteMediaItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaItemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    streamMediaItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaItemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media stream (raw bytes or HLS playlist depending on negotiation) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getThumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaItemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JPEG thumbnail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMediaItemSiblings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaItemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sibling items (includes this one) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaItem"][];
                };
            };
        };
    };
    getShow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaItemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Show detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Show"];
                };
            };
            /** @description This item isn't part of a TV show */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaItemId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProgressRequest"];
            };
        };
        responses: {
            /** @description Recorded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaItem"];
                };
            };
        };
    };
    streamChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the external stream */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
