DROP TABLE IF EXISTS watch_state;
DROP TABLE IF EXISTS profile;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS channel;
DROP TABLE IF EXISTS media_item;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS library;
